-- =================================================================================
-- LIMPEZA TOTAL
-- =================================================================================
DROP TABLE IF EXISTS tb_pipeline_node_input;
DROP TABLE IF EXISTS tb_pipeline_node_output;
DROP TABLE IF EXISTS tb_data_contract;
DROP TABLE IF EXISTS tb_global_cache;
DROP TABLE IF EXISTS tb_tag_rule;
DROP TABLE IF EXISTS tb_pipeline_node_decorator;
DROP TABLE IF EXISTS tb_decorator_template;
DROP TABLE IF EXISTS tb_pipeline_node;
DROP TABLE IF EXISTS tb_task_template;
DROP TABLE IF EXISTS tb_pipeline_version;
DROP TABLE IF EXISTS tb_input_normalization;
DROP TABLE IF EXISTS tb_semantic_definition;

-- =================================================================================
-- 1. SEMÂNTICA DE DADOS
-- =================================================================================
CREATE TABLE tb_semantic_definition (
    type_name VARCHAR(50) PRIMARY KEY,
    format_script TEXT,
    plus_script TEXT,
    concat_script TEXT,
    description VARCHAR(255)
);

-- =================================================================================
-- 2. NORMALIZAÇÃO DE ENTRADA
-- =================================================================================
CREATE TABLE tb_input_normalization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type VARCHAR(50) NOT NULL,
    target_field VARCHAR(50) NOT NULL,
    source_signal VARCHAR(50) NOT NULL,
    source_path VARCHAR(255),
    transformation_expression VARCHAR(255)
);

-- =================================================================================
-- 3. VERSÃO DO PIPELINE
-- =================================================================================
CREATE TABLE tb_pipeline_version (
    pipeline_id UUID PRIMARY KEY,
    operation_type VARCHAR(50) NOT NULL,
    version INT NOT NULL,
    timeout_ms BIGINT NOT NULL DEFAULT 30000,
    required_outputs TEXT DEFAULT '[]',
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(operation_type, version)
);

-- =================================================================================
-- 4. TEMPLATES DE TASKS
-- =================================================================================
CREATE TABLE tb_task_template (
    template_id VARCHAR(50) PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    base_configuration TEXT NOT NULL,
    description VARCHAR(255)
);

-- =================================================================================
-- 5. NÓS DO PIPELINE
-- =================================================================================
CREATE TABLE tb_pipeline_node (
    node_id UUID PRIMARY KEY,
    pipeline_id UUID NOT NULL,
    template_id VARCHAR(50),
    name VARCHAR(50) NOT NULL,
    type VARCHAR(20),
    configuration TEXT,
    activation_tags TEXT DEFAULT '["default"]',
    guard_condition VARCHAR(500),
    fail_fast BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (pipeline_id) REFERENCES tb_pipeline_version(pipeline_id),
    FOREIGN KEY (template_id) REFERENCES tb_task_template(template_id)
);

-- =================================================================================
-- 6. INPUTS DO NÓ (SEPARAÇÃO DE SINAL E DADO)
-- =================================================================================
CREATE TABLE tb_pipeline_node_input (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id UUID NOT NULL,
    local_key VARCHAR(50) NOT NULL,
    source_signal VARCHAR(50) NOT NULL,
    source_path VARCHAR(255),
    expected_semantic_type VARCHAR(50),
    is_required BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (node_id) REFERENCES tb_pipeline_node(node_id),
    FOREIGN KEY (expected_semantic_type) REFERENCES tb_semantic_definition(type_name)
);

-- =================================================================================
-- 7. OUTPUTS DO NÓ (SINAIS PUROS)
-- =================================================================================
CREATE TABLE tb_pipeline_node_output (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id UUID NOT NULL,
    local_key VARCHAR(50) NOT NULL,
    target_signal VARCHAR(50) NOT NULL,
    produced_semantic_type VARCHAR(50),
    FOREIGN KEY (node_id) REFERENCES tb_pipeline_node(node_id),
    FOREIGN KEY (produced_semantic_type) REFERENCES tb_semantic_definition(type_name)
);

-- =================================================================================
-- 8. TEMPLATES DE DECORADORES
-- =================================================================================
CREATE TABLE tb_decorator_template (
    template_id VARCHAR(50) PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    phase VARCHAR(20) NOT NULL DEFAULT 'AROUND',
    default_configuration TEXT NOT NULL,
    description VARCHAR(255)
);

-- =================================================================================
-- 9. ASSOCIAÇÃO DE DECORADORES
-- =================================================================================
CREATE TABLE tb_pipeline_node_decorator (
    node_id UUID NOT NULL,
    template_id VARCHAR(50) NOT NULL,
    override_configuration TEXT,
    execution_order INT NOT NULL DEFAULT 0,
    PRIMARY KEY (node_id, template_id),
    FOREIGN KEY (node_id) REFERENCES tb_pipeline_node(node_id),
    FOREIGN KEY (template_id) REFERENCES tb_decorator_template(template_id)
);

-- =================================================================================
-- 10. REGRAS DE TAGS
-- =================================================================================
CREATE TABLE tb_tag_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR(50) NOT NULL,
    condition_expression VARCHAR(500) NOT NULL,
    priority INT NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE
);

-- =================================================================================
-- 11. CACHE GLOBAL
-- =================================================================================
CREATE TABLE tb_global_cache (
    cache_key VARCHAR(100) PRIMARY KEY,
    cache_value TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================================
-- 12. CONTRATO DE DADOS (RG DOS DADOS)
-- =================================================================================
CREATE TABLE tb_data_contract (
    context_key VARCHAR(100) PRIMARY KEY,
    semantic_type VARCHAR(50),
    format_rule VARCHAR(255),
    schema_definition TEXT,
    min_value DOUBLE,
    max_value DOUBLE,
    is_required BOOLEAN DEFAULT FALSE,
    description VARCHAR(255),
    FOREIGN KEY (semantic_type) REFERENCES tb_semantic_definition(type_name)
);
