-- Limpeza (Para garantir que não haja conflitos no H2 em memória)
DROP TABLE IF EXISTS tb_product_flavors;
DROP TABLE IF EXISTS tb_products;
DROP TABLE IF EXISTS tb_task_catalog;
DROP TABLE IF EXISTS tb_cost_models;
DROP TABLE IF EXISTS tb_infra_profiles;
DROP TABLE IF EXISTS tb_input_normalization;
DROP TABLE IF EXISTS tb_pipeline_config;
DROP TABLE IF EXISTS tb_flow_config;

-- 1. Tabela de Custos (FinOps)
CREATE TABLE tb_cost_models (
    model_id VARCHAR(50) PRIMARY KEY,
    pricing_type VARCHAR(20), -- FIXED, PER_KB
    fixed_cost_brl DECIMAL(10, 6) DEFAULT 0,
    cost_per_kb_brl DECIMAL(10, 6) DEFAULT 0,
    currency VARCHAR(3) DEFAULT 'BRL'
);

-- 2. Perfis de Infraestrutura (Resiliência)
CREATE TABLE tb_infra_profiles (
    profile_id VARCHAR(50) PRIMARY KEY,
    description VARCHAR(255),
    default_controls TEXT -- Configurações padrão
);

-- 2.1 Regras de Tags (Novo)
CREATE TABLE tb_tag_rules (
    tag_name VARCHAR(50) NOT NULL,
    condition_expression VARCHAR(500) NOT NULL,
    priority INT DEFAULT 0,
    description VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (tag_name, condition_expression)
);

-- 3. Catálogo de Tasks (O Coração) - COM VERSIONAMENTO E SCHEMA
CREATE TABLE tb_task_catalog (
    task_id VARCHAR(50) NOT NULL,
    version INT NOT NULL DEFAULT 1,

    task_type VARCHAR(20) NOT NULL,
    task_group VARCHAR(50),
    description VARCHAR(255),
    selector_expression VARCHAR(255),

    -- Load Shedding (0-100). 100 = Crítico, 0 = Descartável.
    criticality INT DEFAULT 100,

    requires_json TEXT,
    produces_json TEXT,

    config_json TEXT,
    features_json TEXT, -- Nome sincronizado com TaskCatalogEntity

    response_schema TEXT, -- JSON Schema para validação de output

    cost_model_id VARCHAR(50),
    infra_profile_id VARCHAR(50),

    is_active BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (task_id, version),
    FOREIGN KEY (cost_model_id) REFERENCES tb_cost_models(model_id),
    FOREIGN KEY (infra_profile_id) REFERENCES tb_infra_profiles(profile_id)
);

-- Índices para performance
CREATE INDEX idx_task_active ON tb_task_catalog(is_active);

-- 4. Catálogo de Produtos (A Vitrine)
CREATE TABLE tb_products (
    product_id VARCHAR(50) PRIMARY KEY,
    description VARCHAR(255),
    required_output VARCHAR(50), -- O que o produto promete entregar
    base_tags TEXT,              -- Tags injetadas automaticamente
    sla_timeout_ms INT DEFAULT 1000
);

-- 5. Sabores/Variações do Produto
CREATE TABLE tb_product_flavors (
    flavor_id VARCHAR(50) PRIMARY KEY,
    product_id VARCHAR(50),
    description VARCHAR(255),
    parameters TEXT, -- Parâmetros de calibragem (Scores, Limites)

    FOREIGN KEY (product_id) REFERENCES tb_products(product_id)
);

-- 6. Normalização de Entrada (Adapters)
CREATE TABLE tb_input_normalization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type VARCHAR(50), -- Mudado de client_id
    target_field VARCHAR(50), -- Campo padrão (#standard.cpf)
    source_expression VARCHAR(255), -- Onde buscar no raw (#raw.documento)
    transformation_expression VARCHAR(255) -- Transformação opcional
);

-- 7. Catálogo de Erros Customizados (Banco de Exceptions)
CREATE TABLE tb_error_catalog (
    error_code VARCHAR(50) PRIMARY KEY,
    message_template VARCHAR(500) NOT NULL
);

-- 8. Templates de Features (Configurações Reutilizáveis)
CREATE TABLE tb_feature_templates (
    template_id VARCHAR(50) PRIMARY KEY,
    feature_type VARCHAR(50) NOT NULL,
    config_json TEXT NOT NULL,
    description VARCHAR(255)
);

-- 9. Configuração de Pipeline (Timeouts e SLAs)
CREATE TABLE tb_pipeline_config (
    operation_type VARCHAR(50) PRIMARY KEY,
    timeout_ms BIGINT,
    description VARCHAR(255)
);

-- 10. Definição de Fluxos (Flow Definition) - COM VERSIONAMENTO
CREATE TABLE tb_flow_config (
    operation_type VARCHAR(50) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    required_outputs TEXT, -- JSON Array (ex: ["resultado_final"])
    allowed_tasks TEXT,    -- JSON Array de Objetos (ex: [{"id": "taskA", "version": 1}])
    description VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (operation_type, version)
);
