-- Limpeza Radical
DROP TABLE IF EXISTS tb_profile_features;
DROP TABLE IF EXISTS tb_initialization_tasks;
DROP TABLE IF EXISTS tb_flow_tasks;
DROP TABLE IF EXISTS tb_flow_config;
DROP TABLE IF EXISTS tb_task_catalog;
DROP TABLE IF EXISTS tb_infra_profiles;
DROP TABLE IF EXISTS tb_cost_models;
DROP TABLE IF EXISTS tb_tag_rules;
DROP TABLE IF EXISTS tb_products;
DROP TABLE IF EXISTS tb_product_flavors;
DROP TABLE IF EXISTS tb_input_normalization;
DROP TABLE IF EXISTS tb_error_catalog;
DROP TABLE IF EXISTS tb_feature_templates;
DROP TABLE IF EXISTS tb_pipeline_config;
DROP TABLE IF EXISTS tb_initialization_plan;

-- 1. FinOps e Infra
CREATE TABLE tb_cost_models (
    model_id VARCHAR(50) PRIMARY KEY,
    pricing_type VARCHAR(20),
    fixed_cost_brl DECIMAL(10, 6) DEFAULT 0,
    cost_per_kb_brl DECIMAL(10, 6) DEFAULT 0,
    currency VARCHAR(3) DEFAULT 'BRL'
);

CREATE TABLE tb_infra_profiles (
    profile_id VARCHAR(50) PRIMARY KEY,
    description VARCHAR(255)
);

-- 2. Templates de Features
CREATE TABLE tb_feature_templates (
    template_id VARCHAR(50) PRIMARY KEY,
    feature_type VARCHAR(50) NOT NULL,
    config_json TEXT NOT NULL,
    description VARCHAR(255)
);

-- 2.1 Ligação Perfil -> Features (Sem Ordem, a ordem vem do tipo/fase)
CREATE TABLE tb_profile_features (
    profile_id VARCHAR(50),
    template_id VARCHAR(50),
    phase VARCHAR(20),
    PRIMARY KEY (profile_id, template_id, phase),
    FOREIGN KEY (profile_id) REFERENCES tb_infra_profiles(profile_id),
    FOREIGN KEY (template_id) REFERENCES tb_feature_templates(template_id)
);

-- 3. Catálogo de Tasks
CREATE TABLE tb_task_catalog (
    task_id VARCHAR(50) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    task_type VARCHAR(20) NOT NULL,
    task_group VARCHAR(50),
    description VARCHAR(255),
    selector_expression TEXT,
    criticality INT DEFAULT 100,
    requires_json TEXT,
    produces_json TEXT,
    config_json TEXT,
    features_json TEXT,
    response_schema TEXT,
    infra_profile_id VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    jpa_version BIGINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (task_id, version),
    FOREIGN KEY (infra_profile_id) REFERENCES tb_infra_profiles(profile_id)
);

-- 4. Fluxos e Inicialização
CREATE TABLE tb_flow_config (
    operation_type VARCHAR(50) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    required_outputs TEXT,
    description VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (operation_type, version)
);

CREATE TABLE tb_flow_tasks (
    operation_type VARCHAR(50) NOT NULL,
    flow_version INT NOT NULL,
    task_id VARCHAR(50) NOT NULL,
    task_version INT NOT NULL,
    PRIMARY KEY (operation_type, flow_version, task_id, task_version),
    FOREIGN KEY (operation_type, flow_version) REFERENCES tb_flow_config(operation_type, version),
    FOREIGN KEY (task_id, task_version) REFERENCES tb_task_catalog(task_id, version)
);

-- 4.1 Plano de Inicialização
CREATE TABLE tb_initialization_plan (
    operation_type VARCHAR(50) PRIMARY KEY,
    description VARCHAR(255)
);

CREATE TABLE tb_initialization_tasks (
    operation_type VARCHAR(50),
    task_id VARCHAR(50),
    task_version INT,
    PRIMARY KEY (operation_type, task_id, task_version),
    FOREIGN KEY (operation_type) REFERENCES tb_initialization_plan(operation_type),
    FOREIGN KEY (task_id, task_version) REFERENCES tb_task_catalog(task_id, version)
);

-- 5. Configurações Tipadas
CREATE TABLE tb_pipeline_config (
    operation_type VARCHAR(50) PRIMARY KEY,
    timeout_ms BIGINT NOT NULL,
    description VARCHAR(255)
);

-- Outras tabelas
CREATE TABLE tb_tag_rules (
    tag_name VARCHAR(50) NOT NULL,
    condition_expression VARCHAR(500) NOT NULL,
    priority INT DEFAULT 0,
    description VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (tag_name, condition_expression)
);

CREATE TABLE tb_input_normalization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type VARCHAR(50),
    target_field VARCHAR(50),
    source_expression VARCHAR(255),
    transformation_expression VARCHAR(255)
);

CREATE TABLE tb_error_catalog (
    error_code VARCHAR(50) PRIMARY KEY,
    message_template VARCHAR(500) NOT NULL
);
